name: Deploy CodeIgniter Frontend via FTP

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  ftp-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar lftp
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # 3. Desplegar vía FTP
      - name: FTP Deploy CodeIgniter to gciil.com
        env:
          FTP_HOST: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" << 'EOF'
            set ftp:ssl-allow no

            # Opcional: exclude de carpetas generadas
            lcd .

            # Mirror de todo el proyecto al root del hosting
            mirror --reverse \
                   --delete \
                   --verbose \
                   --exclude .git* \
                   --exclude writable/cache \
                   --exclude writable/debugbar \
                   --exclude writable/session \
                   --exclude writable/uploads \
                   --exclude vendor \
                   . /public_html/

            bye
          EOF
